import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/sections/Navbar'
import Hero from '@/components/sections/Hero'
import About from '@/components/sections/About'

export const metadata: Metadata = {
  title: 'Kristiyan Cholakov',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Navbar />
        <Hero />
        <About />
        <main className="pt-16">{children}</main>
      </body>
    </html>
  )
}
